version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - run: npm install yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build
