export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const PROJECT_SAVE_START = 'PROJECT_SAVE_START';
export const PROJECT_SAVE_SUCCESS = 'PROJECT_SAVE_SUCCESS';
export const PROJECT_SAVE_FAILED = 'PROJECT_SAVE_FAILED';

export const PROJECTS_GET_START = 'PROJECTS_GET_START';
export const PROJECTS_GET_SUCCESS = 'PROJECTS_GET_SUCCESS';
export const PROJECTS_GET_FAILED = 'PROJECTS_GET_FAILED';
